"""Generate LaTeX tables/snippets directly from results CSVs.

This keeps the paper as a thin view over `code/results/*.csv` (single source of truth).
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd


METHOD_DISPLAY = {
    "non_private_dr": "Non-private DR",
    "mst_naive": "MST + naive",
    "aim_naive": "AIM + naive",
    "causal_naive": "Causal + naive",
    "causal_na_mi": "Causal + NA+MI",
    "causal_aim_na_mi": "Causal-AIM + NA+MI",
    "fixed_causal": "Fixed causal workload",
    "causal_aim": "Causal-AIM",
}

DATASET_DISPLAY = {
    "ihdp": "IHDP",
    "twins": "Twins",
    "acic_dgp7": "ACIC",
    "lalonde": "LaLonde",
    "acs": "ACS",
}


def _read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def _fmt(x: float) -> str:
    if not np.isfinite(x):
        return "nan"
    return f"{float(x):.3f}"


def _fmt_marked(x: float, bold: bool = False, underline: bool = False) -> str:
    s = _fmt(x)
    if underline:
        s = rf"\underline{{{s}}}"
    if bold:
        s = rf"\textbf{{{s}}}"
    return s


def _rank_targets(values: Iterable[float], higher_is_better: bool = False) -> Tuple[float, float | None]:
    ordered = sorted(
        (float(v) for v in values if np.isfinite(v)),
        reverse=higher_is_better,
    )
    unique: List[float] = []
    for v in ordered:
        if not any(np.isclose(v, u) for u in unique):
            unique.append(v)
    best = unique[0]
    second = unique[1] if len(unique) > 1 else None
    return best, second


def _table_row(
    method_key: str,
    cells: Iterable[Tuple[float, float, bool, bool, bool, bool]],
) -> str:
    method_name = METHOD_DISPLAY.get(method_key, method_key)
    entries = [
        f"{_fmt_marked(r, br, ur)}/{_fmt_marked(c, bc, uc)}"
        for r, c, br, bc, ur, uc in cells
    ]
    return " & ".join([method_name] + entries) + r" \\"


def write_table1(exp1_summary: pd.DataFrame, out_path: Path, epsilon: float = 1.0) -> None:
    methods = [
        "non_private_dr",
        "mst_naive",
        "aim_naive",
        "causal_naive",
        "causal_na_mi",
        "causal_aim_na_mi",
    ]
    datasets = ["ihdp", "twins", "acic_dgp7", "lalonde"]

    lines: List[str] = []
    lines.append("% Auto-generated by code/generate_paper_artifacts.py. Do not hand-edit.")

    if exp1_summary.empty:
        lines.append("% Missing exp1_summary.csv; cannot generate Table 1.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    df = exp1_summary.copy()
    df = df[np.isclose(df["epsilon"].astype(float), float(epsilon))]
    if df.empty:
        lines.append(f"% No rows found for epsilon={epsilon}.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    pv = df.pivot_table(index="method", columns="dataset", values=["rmse", "coverage"], aggfunc="first")

    lines.append(r"\begin{table*}[t]")
    lines.append(rf"\caption{{ATE RMSE and 95\% CI Coverage at $\eps={epsilon}$, $\del=1/n^2$. Each cell is RMSE / Coverage; among private methods, bold marks the best value and underlining marks the second-best value in each dataset column.}}")
    lines.append(r"\centering")
    lines.append(r"\begin{tabular}{lcccc}")
    lines.append(r"\toprule")
    lines.append(r"Method & IHDP & Twins & ACIC & LaLonde \\")
    lines.append(r"\midrule")

    private_methods = [m for m in methods if m != "non_private_dr"]
    rmse_ranks = {
        d: _rank_targets((float(pv.loc[m, ("rmse", d)]) for m in private_methods))
        for d in datasets
    }
    cov_ranks = {
        d: _rank_targets((float(pv.loc[m, ("coverage", d)]) for m in private_methods), higher_is_better=True)
        for d in datasets
    }

    for m in methods:
        cells = []
        for d in datasets:
            rmse = float(pv.loc[m, ("rmse", d)])
            cov = float(pv.loc[m, ("coverage", d)])
            best_rmse, second_rmse = rmse_ranks[d]
            best_cov, second_cov = cov_ranks[d]
            is_private = m != "non_private_dr"
            bold_rmse = is_private and np.isclose(rmse, best_rmse)
            bold_cov = is_private and np.isclose(cov, best_cov)
            underline_rmse = is_private and second_rmse is not None and np.isclose(rmse, second_rmse)
            underline_cov = is_private and second_cov is not None and np.isclose(cov, second_cov)
            cells.append((rmse, cov, bool(bold_rmse), bool(bold_cov), bool(underline_rmse), bool(underline_cov)))
        lines.append(_table_row(m, cells))

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\label{tab:main-results}")
    lines.append(r"\end{table*}")

    out_path.write_text("\n".join(lines) + "\n")


def write_exp1_prose(exp1_summary: pd.DataFrame, out_path: Path, epsilon: float = 0.5) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by code/generate_paper_artifacts.py. Do not hand-edit.")

    if exp1_summary.empty:
        lines.append("% Missing exp1_summary.csv; cannot generate Experiment 1 prose.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    df = exp1_summary.copy()
    df = df[np.isclose(df["epsilon"].astype(float), float(epsilon))].copy()
    if df.empty:
        lines.append(f"% No rows found for epsilon={epsilon}.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    n_rep = int(df["n_rep"].iloc[0]) if "n_rep" in df.columns else -1
    datasets = ["ihdp", "twins", "acic_dgp7", "lalonde"]
    methods = ["causal_na_mi", "mst_naive", "aim_naive"]
    label = " / ".join(METHOD_DISPLAY.get(m, m) for m in methods)

    pv = df.pivot_table(index="method", columns="dataset", values="rmse", aggfunc="first")
    parts = []
    for ds in datasets:
        vals = [float(pv.loc[m, ds]) for m in methods]
        parts.append(rf"{DATASET_DISPLAY.get(ds, ds)} {_fmt(vals[0])} / {_fmt(vals[1])} / {_fmt(vals[2])}")

    lines.append(rf"At $\eps={epsilon}$, RMSEs for ({label}) were: " + "; ".join(parts) + (rf" ($n_{{\mathrm{{rep}}}}={n_rep}$)." if n_rep > 0 else "."))
    out_path.write_text("\n".join(lines) + "\n")


def write_exp2_prose(exp2_coverage: pd.DataFrame, out_path: Path, epsilon: float = 0.5) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by code/generate_paper_artifacts.py. Do not hand-edit.")

    if exp2_coverage.empty:
        lines.append("% Missing exp2_coverage.csv; cannot generate Experiment 2 prose.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    df = exp2_coverage.copy()
    df = df[np.isclose(df["epsilon"].astype(float), float(epsilon))].copy()
    if df.empty:
        lines.append(f"% No rows found for epsilon={epsilon}.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    methods = ["mst_naive", "aim_naive", "causal_naive", "causal_na_mi"]

    def _coverage_line(dataset: str) -> str:
        dd = df[df["dataset"] == dataset].set_index("method")
        vals = [float(dd.loc[m, "coverage"]) for m in methods]
        n_reps = int(dd["n_reps"].iloc[0]) if "n_reps" in dd.columns else int(dd["n_rep"].iloc[0]) if "n_rep" in dd.columns else -1
        return (
            rf"At $\eps={epsilon}$ on {DATASET_DISPLAY.get(dataset, dataset)}, coverage was "
            + ", ".join([rf"{_fmt(v)} ({METHOD_DISPLAY.get(m, m)})" for v, m in zip(vals, methods)])
            + (rf" ($n_{{\mathrm{{rep}}}}={n_reps}$)." if n_reps > 0 else ".")
        )

    lines.append(_coverage_line("ihdp"))
    lines.append(_coverage_line("lalonde"))
    out_path.write_text("\n".join(lines) + "\n")


def write_exp3_prose(exp3_summary: pd.DataFrame, out_path: Path, K: int = 5) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by code/generate_paper_artifacts.py. Do not hand-edit.")

    if exp3_summary.empty:
        lines.append("% Missing exp3_summary.csv; cannot generate Experiment 3 prose.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    df = exp3_summary.copy()
    df = df[df["K"] == int(K)].copy()
    if df.empty:
        lines.append(f"% No rows found for K={K}.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    n_rep = int(df["n_rep"].iloc[0]) if "n_rep" in df.columns else -1
    lines.append(rf"Pilot results ($n_{{\mathrm{{rep}}}}={n_rep}$) at $K={K}$:")

    for eps in sorted(df["epsilon"].unique().tolist()):
        d_eps = df[np.isclose(df["epsilon"].astype(float), float(eps))].set_index("method")
        if "causal_aim" not in d_eps.index or "fixed_causal" not in d_eps.index:
            continue
        rmse_a = float(d_eps.loc["causal_aim", "rmse"])
        rmse_f = float(d_eps.loc["fixed_causal", "rmse"])
        red = 0.0 if rmse_f <= 1e-12 else 100.0 * (1.0 - rmse_a / rmse_f)
        if red >= 0:
            red_str = rf"{_fmt(red)}\% reduction"
        else:
            red_str = rf"{_fmt(abs(red))}\% increase"
        lines.append(
            rf"At $\eps={_fmt(eps)}$, RMSE was {_fmt(rmse_a)} ({METHOD_DISPLAY['causal_aim']}) vs. {_fmt(rmse_f)} ({METHOD_DISPLAY['fixed_causal']}) ({red_str})."
        )

    out_path.write_text("\n".join(lines) + "\n")


def write_exp4_prose(exp4_summary: pd.DataFrame, out_path: Path, n_target: int = 1000, epsilon: float = 0.5) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by code/generate_paper_artifacts.py. Do not hand-edit.")

    if exp4_summary.empty:
        lines.append("% Missing exp4_summary.csv; cannot generate Experiment 4 prose.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    df = exp4_summary.copy()
    df = df[(df["n_target"] == int(n_target)) & (np.isclose(df["epsilon"].astype(float), float(epsilon)))].copy()
    if df.empty:
        lines.append(f"% No rows found for n_target={n_target}, epsilon={epsilon}.")
        out_path.write_text("\n".join(lines) + "\n")
        return

    n_rep = int(df["n_rep"].iloc[0]) if "n_rep" in df.columns else -1
    lines.append(rf"Pilot ACS cell ($n_{{\mathrm{{rep}}}}={n_rep}$) at $(n={n_target},\ \eps={epsilon})$:")

    order = [
        "non_private_dr",
        "mst_naive",
        "aim_naive",
        "causal_naive",
        "causal_na_mi",
        "causal_aim_na_mi",
    ]
    d2 = df.set_index("method")
    cov_parts = []
    rmse_parts = []
    for m in order:
        if m not in d2.index:
            continue
        cov_parts.append(rf"{METHOD_DISPLAY.get(m,m)} {_fmt(float(d2.loc[m,'coverage']))}")
        rmse_parts.append(rf"{METHOD_DISPLAY.get(m,m)} {_fmt(float(d2.loc[m,'rmse']))}")

    lines.append("Coverage: " + ", ".join(cov_parts) + ".")
    lines.append("RMSE: " + ", ".join(rmse_parts) + ".")
    out_path.write_text("\n".join(lines) + "\n")


def write_ablation_prose(
    ab_dim: pd.DataFrame,
    ab_mi: pd.DataFrame,
    ab_nsyn: pd.DataFrame,
    ab_overlap: pd.DataFrame,
    out_path: Path,
) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by code/generate_paper_artifacts.py. Do not hand-edit.")

    if not ab_dim.empty:
        df = ab_dim.sort_values("bins")
        p_vals = [int(x) for x in df["p"].tolist()]
        rmse_vals = [float(x) for x in df["rmse"].tolist()]
        var_vals = [float(x) for x in df["variance_component"].tolist()] if "variance_component" in df.columns else []
        n_rep = int(df["n_rep"].iloc[0]) if "n_rep" in df.columns else -1
        lines.append(
            rf"Workload size ablation ($n_{{\mathrm{{rep}}}}={n_rep}$): $p \in \{{{', '.join(map(str,p_vals))}\}}$ with RMSE "
            + ", ".join(_fmt(x) for x in rmse_vals)
            + ("; variance component " + ", ".join(_fmt(x) for x in var_vals) if var_vals else "")
            + "."
        )
    else:
        lines.append("% Missing ablation_workload_dim.csv.")

    if not ab_mi.empty:
        df = ab_mi.sort_values("M")
        m_vals = [int(x) for x in df["M"].tolist()]
        cov_vals = [float(x) for x in df["coverage"].tolist()]
        n_rep = int(df["n_rep"].iloc[0]) if "n_rep" in df.columns else -1
        lines.append(
            rf"MI draws ablation ($n_{{\mathrm{{rep}}}}={n_rep}$): coverage for $M \in \{{{', '.join(map(str,m_vals))}\}}$ was "
            + ", ".join(_fmt(x) for x in cov_vals)
            + "."
        )
    else:
        lines.append("% Missing ablation_mi_draws.csv.")

    if not ab_nsyn.empty:
        df = ab_nsyn.sort_values("ratio")
        ratios = [int(x) for x in df["ratio"].tolist()]
        rmses = [float(x) for x in df["rmse"].tolist()]
        n_rep = int(df["n_rep"].iloc[0]) if "n_rep" in df.columns else -1
        lines.append(
            rf"Synthetic size ablation ($n_{{\mathrm{{rep}}}}={n_rep}$): RMSE for $n_{{\mathrm{{syn}}}}/n \in \{{{', '.join(map(str,ratios))}\}}$ was "
            + ", ".join(_fmt(x) for x in rmses)
            + "."
        )
    else:
        lines.append("% Missing ablation_nsyn.csv.")

    if not ab_overlap.empty and ("n_rep" in ab_overlap.columns) and int(ab_overlap["n_rep"].max()) > 1:
        n_rep = int(ab_overlap["n_rep"].max())
        lines.append(rf"Overlap ablation ($n_{{\mathrm{{rep}}}}={n_rep}$): see Figure~\ref{{fig:ablation_overlap}}.")
    else:
        n_rep = int(ab_overlap["n_rep"].max()) if ("n_rep" in ab_overlap.columns and not ab_overlap.empty) else -1
        lines.append(rf"Overlap ablation omitted (current $n_{{\mathrm{{rep}}}}={n_rep}$).")

    out_path.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate LaTeX artifacts from Paper 2 CSV results")
    parser.add_argument("--results-dir", type=str, default="results")
    parser.add_argument("--out-dir", type=str, default="../auto")
    args = parser.parse_args()

    results_dir = Path(args.results_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    exp1 = _read_csv(results_dir / "exp1_summary.csv")
    exp2_cov = _read_csv(results_dir / "exp2_coverage.csv")
    exp3 = _read_csv(results_dir / "exp3_summary.csv")
    exp4 = _read_csv(results_dir / "exp4_summary.csv")
    ab_dim = _read_csv(results_dir / "ablation_workload_dim.csv")
    ab_mi = _read_csv(results_dir / "ablation_mi_draws.csv")
    ab_nsyn = _read_csv(results_dir / "ablation_nsyn.csv")
    ab_overlap = _read_csv(results_dir / "ablation_overlap.csv")

    write_table1(exp1_summary=exp1, out_path=out_dir / "table1.tex", epsilon=1.0)
    write_exp1_prose(exp1_summary=exp1, out_path=out_dir / "exp1_prose.tex", epsilon=0.5)
    write_exp2_prose(exp2_coverage=exp2_cov, out_path=out_dir / "exp2_prose.tex", epsilon=0.5)
    write_exp3_prose(exp3_summary=exp3, out_path=out_dir / "exp3_prose.tex", K=5)
    write_exp4_prose(exp4_summary=exp4, out_path=out_dir / "exp4_prose.tex", n_target=1000, epsilon=0.5)
    write_ablation_prose(
        ab_dim=ab_dim,
        ab_mi=ab_mi,
        ab_nsyn=ab_nsyn,
        ab_overlap=ab_overlap,
        out_path=out_dir / "ablations_prose.tex",
    )

    print(f"Wrote LaTeX artifacts to {out_dir}")


if __name__ == "__main__":
    main()
